alter table advert drop constraint FKAB3E6FD498F74861
alter table link_category_advert drop constraint FKA7C387F0E9F1A441
alter table link_category_advert drop constraint FKA7C387F0EC2C23D0
alter table phone drop constraint FK65B3D6E98F74861
drop table aduser if exists
drop table advert if exists
drop table category if exists
drop table link_category_advert if exists
drop table phone if exists
create table aduser (
   id bigint generated by default as identity (start with 1),
   name varchar(255),
   password varchar(255),
   primary key (id),
   unique (name)
)
create table advert (
   id bigint generated by default as identity (start with 1),
   message varchar(255),
   title varchar(255),
   aduser bigint not null,
   primary key (id)
)
create table category (
   id bigint generated by default as identity (start with 1),
   title varchar(255),
   primary key (id),
   unique (title)
)
create table link_category_advert (
   id bigint not null,
   advert bigint not null,
   primary key (id, advert)
)
create table phone (
   id bigint generated by default as identity (start with 1),
   number varchar(255),
   comment varchar(255),
   aduser bigint not null,
   primary key (id)
)
alter table advert add constraint FKAB3E6FD498F74861 foreign key (aduser) references aduser
alter table link_category_advert add constraint FKA7C387F0E9F1A441 foreign key (id) references category
alter table link_category_advert add constraint FKA7C387F0EC2C23D0 foreign key (advert) references advert
alter table phone add constraint FK65B3D6E98F74861 foreign key (aduser) references aduser
